A matrix: 

[[0.0313 0.6262 0.4547 ... 0.5567 0.0618 0.1694]
 [0.9984 0.5157 0.0959 ... 0.9467 0.1096 0.9884]
 [0.3873 0.7749 0.9583 ... 0.6551 0.7479 0.413 ]
 ...
 [0.8438 0.2985 0.9935 ... 0.6751 0.9589 0.5493]
 [0.2845 0.7831 0.2635 ... 0.4627 0.5296 0.9735]
 [0.6024 0.765  0.1164 ... 0.2904 0.6108 0.4041]]
B matrix: 

[[0.3136 0.5987 0.2989 ... 0.8385 0.5252 0.1862]
 [0.8216 0.1506 0.3883 ... 0.5855 0.7318 0.4323]
 [0.3202 0.4613 0.6255 ... 0.3386 0.043  0.7138]
 ...
 [0.2179 0.7144 0.5134 ... 0.3146 0.4908 0.9389]
 [0.2339 0.7995 0.6588 ... 0.8096 0.1035 0.2219]
 [0.0722 0.1612 0.5506 ... 0.5921 0.8872 0.351 ]]
RPC_SYNC DONE
C transfer done
Timestamps transfer done
[[4.5977246e+03 4.5579814e+03 4.5731416e+03 ... 4.5817295e+03
  4.5298379e+03 4.5461045e+03]
 [4.5929077e+03 4.5932114e+03 4.5891880e+03 ... 4.6207432e+03
  4.5597373e+03 4.5630000e+03]
 [4.5637339e+03 4.5442773e+03 4.5529858e+03 ... 4.5754673e+03
  4.5432158e+03 4.5250591e+03]
 ...
 [4.5989375e+03 4.5884868e+03 4.5842471e+03 ... 4.6007822e+03
  4.5450728e+03 4.5304116e+03]
 [4.5911279e+03 4.5965244e+03 4.5861685e+03 ... 4.6043696e+03
  4.5523638e+03 4.5405283e+03]
 [4.6022354e+03 4.5757056e+03 4.5739414e+03 ... 5.9958206e+01
  6.4402931e+01 1.4183910e-01]]
[[4597.7437 4557.985  4573.138  ... 4581.7407 4529.851  4546.103 ]
 [4592.9033 4593.225  4589.186  ... 4620.7373 4559.7275 4563.0137]
 [4563.722  4544.276  4552.9756 ... 4575.4644 4543.2227 4525.072 ]
 ...
 [4598.921  4588.4873 4584.244  ... 4600.7896 4545.0767 4530.403 ]
 [4591.1265 4596.5264 4586.163  ... 4604.372  4552.36   4540.5186]
 [4602.2397 4575.6997 4573.9385 ... 4613.6133 4549.394  4569.2104]]
2091371.3870588236
Traceback (most recent call last):
  File "./run.py", line 170, in <module>
    np.testing.assert_allclose(C_expected, C, rtol=1e-05, atol=1e-06)
  File "/python/python-x86_64/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1592, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/cb/toolchains/buildroot/monolith-default/202403181828-238-5e1418a5/rootfs-x86_64/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/python/python-x86_64/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 862, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-06

Mismatched elements: 540238 / 334890000 (0.161%)
Max absolute difference: 4701.2974
Max relative difference: 1.8672612e+09
 x: array([[4597.7437, 4557.985 , 4573.138 , ..., 4581.7407, 4529.851 ,
        4546.103 ],
       [4592.9033, 4593.225 , 4589.186 , ..., 4620.7373, 4559.7275,...
 y: array([[4.597725e+03, 4.557981e+03, 4.573142e+03, ..., 4.581729e+03,
        4.529838e+03, 4.546104e+03],
       [4.592908e+03, 4.593211e+03, 4.589188e+03, ..., 4.620743e+03,...
Program completed in: 00:04:21
