COUT002 22:07:22 GMT  ERROR: LOGGER NOT INITIALIZED:
COUT002 22:07:22 GMT  ERROR: 		Remote end closed connection
M: 42699, K: 30100, N: 32207, Mt: 43, Kt: 43, Nt: 43, Pr: 993, Cycle: 700, Pc: 749, channel: 1, buffer: 0
RPC_SYNC DONE
C transfer done
Timestamps transfer done
13211976.688235294
Traceback (most recent call last):
  File "./run.py", line 175, in <module>
    np.testing.assert_allclose(C_expected, C, rtol=1e-05, atol=1e-06)
  File "/python/python-x86_64/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 1592, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/cb/toolchains/buildroot/monolith-default/202403181828-238-5e1418a5/rootfs-x86_64/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/python/python-x86_64/lib/python3.8/site-packages/numpy/testing/_private/utils.py", line 862, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-06

Mismatched elements: 38189 / 1375206693 (0.00278%)
Max absolute difference: 0.10839844
Max relative difference: 1.4512122e-05
 x: array([[7555.4385, 7526.6206, 7539.7266, ..., 7547.667 , 7549.437 ,
        7534.1978],
       [7500.0713, 7472.199 , 7516.7236, ..., 7522.3867, 7540.507 ,...
 y: array([[7555.441 , 7526.6284, 7539.7324, ..., 7547.6875, 7549.4536,
        7534.191 ],
       [7500.0664, 7472.1807, 7516.723 , ..., 7522.3667, 7540.492 ,...
Program completed in: 00:22:39
